/*
 * Generated by dtrace(1M).
 */

#ifndef	_NEW_DTRACE_H
#define	_NEW_DTRACE_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define MACRUBY_STABILITY "___dtrace_stability$macruby$v1$1_1_0_1_1_0_1_1_0_1_1_0_1_1_0"

#define MACRUBY_TYPEDEFS "___dtrace_typedefs$macruby$v1"

#define	MACRUBY_INSN_ENTRY(arg0, arg1, arg2) \
{ \
	__asm__ volatile(".reference " MACRUBY_TYPEDEFS); \
	__dtrace_probe$macruby$insn__entry$v1$63686172202a$63686172202a$696e74(arg0, arg1, arg2); \
	__asm__ volatile(".reference " MACRUBY_STABILITY); \
} 
#define	MACRUBY_INSN_ENTRY_ENABLED() \
	__dtrace_isenabled$macruby$insn__entry$v1()
#define	MACRUBY_INSN_RETURN(arg0, arg1, arg2) \
{ \
	__asm__ volatile(".reference " MACRUBY_TYPEDEFS); \
	__dtrace_probe$macruby$insn__return$v1$63686172202a$63686172202a$696e74(arg0, arg1, arg2); \
	__asm__ volatile(".reference " MACRUBY_STABILITY); \
} 
#define	MACRUBY_INSN_RETURN_ENABLED() \
	__dtrace_isenabled$macruby$insn__return$v1()
#define	MACRUBY_METHOD_ENTRY(arg0, arg1, arg2, arg3) \
{ \
	__asm__ volatile(".reference " MACRUBY_TYPEDEFS); \
	__dtrace_probe$macruby$method__entry$v1$63686172202a$63686172202a$63686172202a$696e74(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " MACRUBY_STABILITY); \
} 
#define	MACRUBY_METHOD_ENTRY_ENABLED() \
	__dtrace_isenabled$macruby$method__entry$v1()
#define	MACRUBY_METHOD_RETURN(arg0, arg1, arg2, arg3) \
{ \
	__asm__ volatile(".reference " MACRUBY_TYPEDEFS); \
	__dtrace_probe$macruby$method__return$v1$63686172202a$63686172202a$63686172202a$696e74(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " MACRUBY_STABILITY); \
} 
#define	MACRUBY_METHOD_RETURN_ENABLED() \
	__dtrace_isenabled$macruby$method__return$v1()
#define	MACRUBY_RAISE(arg0, arg1, arg2) \
{ \
	__asm__ volatile(".reference " MACRUBY_TYPEDEFS); \
	__dtrace_probe$macruby$raise$v1$63686172202a$63686172202a$696e74(arg0, arg1, arg2); \
	__asm__ volatile(".reference " MACRUBY_STABILITY); \
} 
#define	MACRUBY_RAISE_ENABLED() \
	__dtrace_isenabled$macruby$raise$v1()
#define	MACRUBY_RESCUE(arg0, arg1) \
{ \
	__asm__ volatile(".reference " MACRUBY_TYPEDEFS); \
	__dtrace_probe$macruby$rescue$v1$63686172202a$696e74(arg0, arg1); \
	__asm__ volatile(".reference " MACRUBY_STABILITY); \
} 
#define	MACRUBY_RESCUE_ENABLED() \
	__dtrace_isenabled$macruby$rescue$v1()


extern void __dtrace_probe$macruby$insn__entry$v1$63686172202a$63686172202a$696e74(char *, char *, int);
extern int __dtrace_isenabled$macruby$insn__entry$v1(void);
extern void __dtrace_probe$macruby$insn__return$v1$63686172202a$63686172202a$696e74(char *, char *, int);
extern int __dtrace_isenabled$macruby$insn__return$v1(void);
extern void __dtrace_probe$macruby$method__entry$v1$63686172202a$63686172202a$63686172202a$696e74(char *, char *, char *, int);
extern int __dtrace_isenabled$macruby$method__entry$v1(void);
extern void __dtrace_probe$macruby$method__return$v1$63686172202a$63686172202a$63686172202a$696e74(char *, char *, char *, int);
extern int __dtrace_isenabled$macruby$method__return$v1(void);
extern void __dtrace_probe$macruby$raise$v1$63686172202a$63686172202a$696e74(char *, char *, int);
extern int __dtrace_isenabled$macruby$raise$v1(void);
extern void __dtrace_probe$macruby$rescue$v1$63686172202a$696e74(char *, int);
extern int __dtrace_isenabled$macruby$rescue$v1(void);

#ifdef	__cplusplus
}
#endif

#endif	/* _NEW_DTRACE_H */
