.Dd May 20, 2010
.Dt MACRUBYD 1
.Os
.Sh NAME
.Nm macrubyd
.Nd MacRuby Debugger
.Sh SYNOPSIS
.Nm macrubyd
.Ar path_to_ruby_file
.Op Ar arguments...
.Sh DESCRIPTION
.Nm macrubyd
can be used to debug your MacRuby scripts
.Pp
Please run
.Ar help
within
.Nm macrubyd
to get the list of available commands
.Sh SEE ALSO
.Xr macruby 1 ,
.Xr macirb 1 ,
.Xr macrubyc 1 ,
.Xr macruby_deploy 1
