#!/bin/bash

# create the symbolic link of rb_nibtool
NIBTOOL=/Library/Frameworks/MacRuby.framework/Versions/Current/usr/bin/rb_nibtool
XCODE_DIR=`xcode-select -print-path`
if test $? -ne 0 ; then
    XCODE_DIR=/Applications/Xcode.app/Contents/Developer/
    if [ ! -e "$XCODE_DIR" ] ; then
	exit 1
    fi
    sudo xcode-select -switch "$XCODE_DIR"
fi

DEST_NIBTOOL_PATH="$XCODE_DIR/Tools/rb_nibtool"
XCODE_MAJOR_VER=`xcodebuild -version | sed -e '2,$d' -e 's/Xcode \([0-9]*\).*/\1/'`
if test $XCODE_MAJOR_VER -le 3 ; then
    DEST_NIBTOOL_PATH="$XCODE_DIR/usr/bin/rb_nibtool"
fi

if [ ! -e "$DEST_NIBTOOL_PATH" ] ; then
    ln -s "$NIBTOOL" "$DEST_NIBTOOL_PATH"
fi

# copy the Examples
USER_EXAMPLE_DIR=~/Documents/MacRubyExamples
mkdir -p "$USER_EXAMPLE_DIR"
cp -R /tmp/macruby/sample-macruby/ "$USER_EXAMPLE_DIR"

exit 0